// src/routes/AdminRoutes.ts
import { Router } from 'express';
import type { Request, Response } from 'express';
import { DiscountService } from '../services/DiscountService.js';
import { orders, discountCodeStore } from '../data/InMemoryStore.js';

const router = Router();

// --- ADMIN API 1: POST /api/v1/admin/discount/generate ---
// Generates a discount code if the last order was nth and a code hasn't been generated yet.
router.post('/discount/generate', (req: Request, res: Response) => {
    try {
        const lastOrder = orders[orders.length - 1];

        if (!lastOrder) {
            return res.status(404).json({ message: 'No orders have been placed yet.' });
        }

        if (!lastOrder.isDiscountEligible) {
            return res.status(403).json({ message: `Order #${lastOrder.id} is not an Nth order and is not eligible.` });
        }
        
        // Generate the code using the service logic
        const newCode = DiscountService.generateCode(lastOrder);

        res.status(200).json({
            message: `Coupon code generated successfully by Order #${lastOrder.id}.`,
            code: newCode.code,
            expires: 'Single Use'
        });

    } catch (error: any) {
        // Handle errors from the DiscountService (e.g., code already exists/generated)
        res.status(400).json({ message: error.message });
    }
});

// --- ADMIN API 2: GET /api/v1/admin/stats ---
// Lists purchase statistics.
router.get('/stats', (req: Request, res: Response) => {
    if (orders.length === 0) {
        return res.status(200).json({ 
            message: 'No purchase data available yet.', 
            stats: { 
                ordersCount: 0,
                itemsPurchased: 0,
                totalRevenue: 0,
                totalDiscountGiven: 0,
                activeDiscountCode: discountCodeStore.code,
                allDiscountCodesGenerated: []
            }
        });
    }

    let itemsPurchased = 0;
    let totalRevenue = 0;
    let totalDiscountGiven = 0;
    const generatedCodes: string[] = [];
    
    // Calculate aggregate statistics by iterating through all placed orders
    for (const order of orders) {
        itemsPurchased += order.items.reduce((sum, item) => sum + item.quantity, 0);
        totalRevenue += order.totalAmount;
        totalDiscountGiven += order.discountApplied;
        
        if (order.status === 'DISCOUNT_GENERATED') {
            // Find the code generated by this order. 
            // In a real database, this would be a lookup, here we can infer it
            // or rely on the single-active-code model for simplicity.
            if (order.couponCodeUsed) {
                 generatedCodes.push(order.couponCodeUsed);
            } else if (discountCodeStore.code && discountCodeStore.code.orderGeneratedBy === order.id) {
                 generatedCodes.push(discountCodeStore.code.code);
            }
        }
    }

    const stats = {
        ordersCount: orders.length,
        itemsPurchased: itemsPurchased,
        totalRevenue: Number(totalRevenue.toFixed(2)),
        totalDiscountGiven: Number(totalDiscountGiven.toFixed(2)),
        // The list of discount codes is represented by the codes used plus the current active one
        listOfDiscountCodes: generatedCodes.concat(discountCodeStore.code && discountCodeStore.code.isValid ? [discountCodeStore.code.code] : []),
        activeDiscountCodeStatus: discountCodeStore.code ? (discountCodeStore.code.isValid ? `Active: ${discountCodeStore.code.code}` : 'Inactive') : 'None Generated'
    };

    res.status(200).json({ stats });
});

export default router;